{{ if .Values.externalIngress.enabled }}
# apiVersion: extensions/v1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app }}-external
spec:
  ingressClassName: nginx
  rules:
{{- if .Values.externalIngress.customHost }}
    - host: {{ .Values.externalIngress.customHost | quote}}
{{- else }}
    - host: {{ .Values.app }}.{{ .Values.externalIngress.hostname }}
{{- end }}
      http:
        paths:
          - path: {{ default "/" .Values.externalIngress.path }}
            pathType: {{ default "Prefix" .Values.externalIngress.pathType }}
            backend:
              service:
                name: {{ .Values.app }}
                port: 
                  number: {{ .Values.service.port }}
{{ end }}
